name: Pipeline CI/CD

on:
  push:
    paths-ignore:
      - 'README.md'
    branches: [ main ]
  pull_request:
    branches: [ main ]

permissions:
  contents: read
  packages: write

jobs:
  cicd:

    runs-on: ubuntu-latest

    steps:
      - name: Obter repositório
        uses: actions/checkout@v4

      - name: Configurar Docker
        uses: docker/setup-buildx-action@v3

      - name: Iniciar serviços
        run: docker compose up -d --build

      - name: Criar ambiente para executar testes com o conda
        uses: conda-incubator/setup-miniconda@v3
        with:
          environment-file: conda.yaml
          activate-environment: OML-final

      - name: Executar testes
        run: conda run --no-capture-output -n OML-final pytest

      - name: Iniciar sessão no repositório do GitHub
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Enviar imagem serviço para o repositório do GitHub
        run: docker push ghcr.io/miguelpissarra/api-service:latest
